config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: %w(new create)

  root to: "contacts#new"

  get '*path', to: redirect('/404.html')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, :last_name, presence: true

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :message, presence: true, length: { maximum: Constant::MESSAGE_LENGTH }

  after_create :send_message

  private
  def send_message
    EmailWorker.perform_async(:send_message, email, message, :deliver_later)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def default_url_options(*args)
    super.merge(locale: params["locale"])
  end

  private
  def set_locale
    lang = Constant::SUPPORTED_LANGUAGES[params["locale"]]
    I18n.locale = lang ? params["locale"] : I18n.default_locale
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = t('controller.contacts.created')
      redirect_to new_contact_path
    else
      render :new
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :phone, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.haml
= render 'shared/error_messages', contact: @contact

%head
  %link{:href => "#{asset_pack_path("media/assets/images/icons/favicon.ico")}", :rel => "icon", :type => "image/png"}/

%body
  .container-contact100
    .wrap-contact100
      = form_with model: @contact, url: contacts_path, local: true, html: { class: "contact100-form validate-form" } do |f|
        %span.contact100-form-title
          = t('views.contact.title')
        = f.label t('views.contact.label.name'), class: "label-input100", for: "first-name"
        .wrap-input100.rs1-wrap-input100.validate-input{ "data-validate": t('views.contact.validate.first_name') }
          = f.text_field :first_name, class: "input100", id: "first-name", placeholder: t('views.contact.placeholder.first_name')
          %span.focus-input100
        .wrap-input100.rs2-wrap-input100.validate-input{ "data-validate": t('views.contact.validate.last_name') }
          = f.text_field :last_name, class: "input100", id: "last_name", placeholder: t('views.contact.placeholder.first_name')
          %span.focus-input100
        = f.label t('views.contact.label.email'), class: "label-input100", for: "email"
        .wrap-input100.validate-input{ "data-validate": t('views.contact.validate.email') }
          = f.email_field :email, class: "input100", id: "email", placeholder: t('views.contact.placeholder.email')
          %span.focus-input100
        = f.label t('views.contact.label.phone'), class: "label-input100", for: "phone"
        .wrap-input100
          = f.text_field :phone, class: "input100", id: "phone", placeholder: t('views.contact.placeholder.phone')
          %span.focus-input100
        = f.label t('views.contact.label.message'), class: "label-input100", for: "message"
        .wrap-input100.validate-input{ "data-validate": t('views.contact.validate.message') }
          = f.text_area :message, class: "input100", id: "message", placeholder: t('views.contact.placeholder.message')
          %span.focus-input100
        .container-contact100-form-btn
          = f.submit t('views.contact.submit'), class: "contact100-form-btn"

      .contact100-more.flex-col-c-m{ style: "background-image: url(#{asset_pack_path("media/assets/images/bg-01.jpg")})" }
        .flex-w.size1.p-b-47
          .txt1.p-r-25
            %span.lnr.lnr-map-marker
          .flex-col.size2
            %span.txt1.p-b-20
              = t('views.contact.address.title')
            %span.txt2
              = t('views.contact.address.text')
        .dis-flex.size1.p-b-47
          .txt1.p-r-25
            %span.lnr.lnr-phone-handset
          .flex-col.size2
            %span.txt1.p-b-20
              = t('views.contact.phone.title')
            %span.txt3
              = t('views.contact.phone.number')
        .dis-flex.size1.p-b-47
          .txt1.p-r-25
            %span.lnr.lnr-envelope
          .flex-col.size2
            %span.txt1.p-b-20
              = t('views.contact.support.title')
            %span.txt3
              = t('views.contact.support.email')

  #dropDownSelect1

= javascript_pack_tag 'main'
= stylesheet_pack_tag 'application'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv": "Content-Type" }/
    %title= t('title')
    %meta{ content: "width=device-width,initial-scale=1", name: "viewport" }/
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %main.mt-5
      = render partial: 'shared/flash'
      .container-fluid.pt-3
        .text-right
          = render 'shared/language_selector'
        = yield

app/views/shared/_error_messages.html.haml
- if contact.errors.any?
  .alert.alert-dismissable.alert-danger
    %h3
      = t('errors.messages.not_saved',                  |
        count: contact.errors.count,                       |
        contact: contact.class.model_name.human.downcase) |
    %ul
      - contact.errors.full_messages.each do |message|
        %li= message

app/views/shared/_flash.html.haml
- flash.each do |klass, msg|
  - types = { error: 'danger', notice: 'info', success: 'success', warning: 'warning' }
  .alert.alert-dismissable{ class: "alert-#{types[klass.try(:to_sym)]}" }
    = msg

app/views/shared/_language_selector.html.haml
%ul
  - Constant::SUPPORTED_LANGUAGES.each do |symbol, language|
    %li
      = link_to t("languages.#{language}"), url_for(locale: symbol)